"""add album_item created_at

Revision ID: 0c6ce92f7428
Revises: 76c7e83beaee
Create Date: 2026-08-19 11:27:53.227755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6ce92f7428'
down_revision: Union[str, None] = '76c7e83beaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_album_items_created_at'), 'album_items', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_items_created_at'), table_name='album_items')
    op.drop_column('album_items', 'created_at')
    # ### end Alembic commands ###
