"""add site settings

Revision ID: 4165665984d6
Revises: b6dad3735bee
Create Date: 2026-08-20 07:36:17.996323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4165665984d6'
down_revision: Union[str, None] = 'b6dad3735bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('site_subtitle', sa.String(length=255), nullable=False),
    sa.Column('footer_text', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('mastodon_url', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the singleton settings row (id=1) with the current defaults so the
    # public /api/settings endpoint always has a row to read.
    site_settings = sa.table(
        'site_settings',
        sa.column('id', sa.Integer),
        sa.column('site_name', sa.String),
        sa.column('site_subtitle', sa.String),
        sa.column('footer_text', sa.String),
        sa.column('github_url', sa.String),
        sa.column('mastodon_url', sa.String),
    )
    op.bulk_insert(
        site_settings,
        [
            {
                'id': 1,
                'site_name': "Jaeyoung's Notes",
                'site_subtitle': 'Engineering journal, since 2021',
                'footer_text': '© 2026 Jaeyoung Kim',
                'github_url': 'https://github.com',
                'mastodon_url': 'https://mastodon.social',
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
