"""add series, blog tags/read_time, album item title

Revision ID: b6dad3735bee
Revises: 0c6ce92f7428
Create Date: 2026-08-19 13:41:23.289471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dad3735bee'
down_revision: Union[str, None] = '0c6ce92f7428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_slug'), 'series', ['slug'], unique=True)
    op.add_column('album_items', sa.Column('title', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('blog_posts', sa.Column('tags', sa.ARRAY(sa.String(length=64)), nullable=False, server_default='{}'))
    op.add_column('blog_posts', sa.Column('read_time', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('blog_posts', sa.Column('series_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'blog_posts_series_id_fkey', 'blog_posts', 'series', ['series_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_posts_series_id_fkey', 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'series_id')
    op.drop_column('blog_posts', 'read_time')
    op.drop_column('blog_posts', 'tags')
    op.drop_column('album_items', 'title')
    op.drop_index(op.f('ix_series_slug'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
